### ISSUE TITLE
Add Instantiate trait to VaultToken

### ISSUE THREAD

**Issue by apollo-pacman** [apollodao/cw-token#9]
@apollo-sturdy Mistakenly removed this, but we actually need it since both `OsmosisDenom` and `Cw4626` require it and these are the only implementations we are actually using as vault tokens.

Dod: Require Instantiate trait on VaultToken trait and remove wrong comment.

**Comment by apolloshab** [comment]
fixed - https://github.com/apollodao/cw-token/commit/5652defa8cfcbe28931941f51ac0a62342f0c498
